### ISSUE TITLE
No components are returning after update

### ISSUE THREAD

**Issue by mdegat01** [ollixx/node-red-contrib-components#15]
After updating to 0.1.12 I realized while my components were still being called, nothing was being returned anymore. So anytime I had a "use component" step in my flows then my flows just ended there.

I realized this was happening because after the update all my component return nodes looked like this:
![Screen Shot 2021-08-16 at 8 33 08 AM](https://user-images.githubusercontent.com/2037026/129564412-a037953a-56d6-47d4-bfd1-a03bf3b14714.png)

It seems a new option was added to give users more control over how the output gets returned. But the configuration shown is broken so I have to go and open each one and change "output port" to "default" on each component return node in order to return to the behavior I had.

Could you update it so these component return nodes keep using the default output port if not otherwise specified instead of requiring users to hunt down and fix all these nodes? Or alternatively is it possible to leverage the new [node red linter](https://github.com/node-red/nrlint) to help with this task? Ensure it identifies these nodes as misconfigured so it highlights them for users?

**Comment by ollixx** [comment]
Hey Mike,
Thanks for reporting the bug. I will fix that tomorrow. I haven't had the chance to checkout the linter, but will sure do.
Stay tuned for another patch

**Comment by ollixx** [comment]
I fixed this issue. Thanks again for reporting.
