### ISSUE TITLE
API - Check the type of 'component_in' API parameters

### ISSUE THREAD

**Issue by RGNagel** [ollixx/node-red-contrib-components#2]
Hello,

I just started using this library and it is very great. It will be very convenient for my application. I have been doing something similar to it by using subflows + assert node + comments to provide similar API.

I would like to suggest an addition: to check the type of each input parameter. If the input type (number, string, boolean, ...) is not the expected type conforming to the defined API, then throw an error. Maybe you could add an option (checkbox) so the user can choose if they want to check or not the types.

Keep up the good work,
Thank you

**Comment by ollixx** [comment]
Hey,
Thanks for your request. It absolutely makes sense to validate the input.

Sorry for the late reply.
I have very little time to work on this project, so it might take while before I actually will consider your request.
BUT: I am still on it and will try to find the time in the near future. 
Cheers

**Comment by ollixx** [comment]
released with 0.1.9
