### ISSUE TITLE
how can a "comp return" node in a "catch" flow be associated with a "comp start"?

### ISSUE THREAD

**Issue by rozek** [ollixx/node-red-contrib-components#24]
I have the following problem: a "component" includes a "file" node that writes some data onto the file system, any I/O errors are caught in a "catch" node. The component itself is part of a "http in"-"http out" flow, i.e., it should return in order to be able to send a proper HTTP response back (e.g., 500 Internal Server Error)

How can I use two separate "comp return" nodes in order to have one exit for success and another one for failure? I would like to keep my component unaware of being part of a "http in"-"http out" flow in order to reuse it in another context as well. Right now, the second one does not recognize its relation to any "comp start" node (as it's flow starts with a "catch" node)

**Comment by rozek** [comment]
as mentioned before: I would like to have two independent returns in order to allow for two independent branches depending on success or failure - even if those two branches will finally by brought together (and, perhaps, end in an "HTTP out")

**Comment by ollixx** [comment]
OK; I create an example to understand. It shows you the solution:

`
[
    {
        "id": "f28378a7.c19d08",
        "type": "inject",
        "z": "6fb9afba.adda",
        "name": "test",
        "props": [],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "x": 150,
        "y": 380,
        "wires": [
            [
                "19b0325f.2d0ede"
            ]
        ]
    },
    {
        "id": "c15f0b7e.fa0b28",
        "type": "component_in",
        "z": "6fb9afba.adda",
        "name": "http test",
        "api": [],
        "x": 140,
        "y": 440,
        "wires": [
            [
                "beee768c.c509c8",
                "a074362d.cd2ae8"
            ]
        ]
    },
    {
        "id": "c7702fe9.911ba",
        "type": "component_out",
        "z": "6fb9afba.adda",
        "name": "OK",
        "mode": "separate",
        "component_definitions_are_NOT_allowed_inside_subflows": true,
        "x": 590,
        "y": 440,
        "wires": []
    },
    {
        "id": "6c30bed4.d302",
        "type": "component_out",
        "z": "6fb9afba.adda",
        "name": "BAD",
        "mode": "separate",
        "component_definitions_are_NOT_allowed_inside_subflows": true,
        "x": 590,
        "y": 520,
        "wires": []
    },
    {
        "id": "4faeeff8.47193",
        "type": "http in",
        "z": "6fb9afba.adda",
        "name": "",
        "url": "/httptest",
        "method": "get",
        "upload": false,
        "swaggerDoc": "",
        "x": 150,
        "y": 580,
        "wires": [
            [
                "dbe5916e.7ed2c"
            ]
        ]
    },
    {
        "id": "deb1b9ff.654cc8",
        "type": "http response",
        "z": "6fb9afba.adda",
        "name": "",
        "statusCode": "",
        "headers": {},
        "x": 640,
        "y": 580,
        "wires": []
    },
    {
        "id": "dbe5916e.7ed2c",
        "type": "component",
        "z": "6fb9afba.adda",
        "name": "",
        "targetComponent": {
            "id": "c15f0b7e.fa0b28",
            "name": "http test",
            "api": []
        },
        "paramSources": {},
        "statuz": "",
        "statuzType": "str",
        "outputs": 2,
        "outLabels": [
            "OK",
            "BAD"
        ],
        "x": 340,
        "y": 580,
        "wires": [
            [
                "deb1b9ff.654cc8"
            ],
            [
                "c2c2d374.933f"
            ]
        ]
    },
    {
        "id": "19b0325f.2d0ede",
        "type": "http request",
        "z": "6fb9afba.adda",
        "name": "",
        "method": "GET",
        "ret": "txt",
        "paytoqs": "ignore",
        "url": "http://localhost:1900/httptest",
        "tls": "",
        "persist": false,
        "proxy": "",
        "authType": "",
        "x": 330,
        "y": 380,
        "wires": [
            [
                "ccd6f788.218b38"
            ]
        ]
    },
    {
        "id": "c2c2d374.933f",
        "type": "change",
        "z": "6fb9afba.adda",
        "name": "404",
        "rules": [
            {
                "t": "set",
                "p": "statusCode",
                "pt": "msg",
                "to": "404",
                "tot": "num"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 500,
        "y": 620,
        "wires": [
            [
                "deb1b9ff.654cc8"
            ]
        ]
    },
    {
        "id": "beee768c.c509c8",
        "type": "file in",
        "z": "6fb9afba.adda",
        "name": "",
        "filename": "IamNotHere.dummy",
        "format": "utf8",
        "chunk": false,
        "sendError": false,
        "encoding": "none",
        "x": 380,
        "y": 440,
        "wires": [
            [
                "c7702fe9.911ba"
            ]
        ]
    },
    {
        "id": "c219b.19555e66",
        "type": "catch",
        "z": "6fb9afba.adda",
        "name": "",
        "scope": [
            "beee768c.c509c8"
        ],
        "uncaught": false,
        "x": 340,
        "y": 520,
        "wires": [
            [
                "6c30bed4.d302"
            ]
        ]
    },
    {
        "id": "a074362d.cd2ae8",
        "type": "function",
        "z": "6fb9afba.adda",
        "name": "trick / work-around",
        "func": "// dont pass on the message!",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "x": 370,
        "y": 480,
        "wires": [
            [
                "6c30bed4.d302"
            ]
        ]
    },
    {
        "id": "ccd6f788.218b38",
        "type": "debug",
        "z": "6fb9afba.adda",
        "name": "Result",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 510,
        "y": 380,
        "wires": []
    }
]
`
I hope that works for you.
The RETURN has to be wired to the START node, but must not receive the message from it. That would work without a workaround, if it was possible to connect the nodes using the edit dialog - in a selection. But I still consider wiring as the easier way to go. Your use case is an edge case, that is probably not very common. But I see, that I need some more examples in the docs.
Thanks for this excellent example!

**Comment by rozek** [comment]
What a brilliant idea!

Indeed, this example works as foreseen. While it looks a bit like a workaround, too, it is definitely one I can live with: don't forget to document it in your README!

By the way: I don't consider error handling as an "edge case" - every flow should include "catch" nodes to ensure proper behaviour even in case of (I/O and programming) errors...

Thanks a lot for your effort!

**Comment by ollixx** [comment]
glad I could help.
Your feedback strongly reminds me about refactoring the README and to provide examples.
Thanks again.
