### ISSUE TITLE
one "comp use" called, but multiple "comp use" return!!!!

### ISSUE THREAD

**Issue by rozek** [ollixx/node-red-contrib-components#27]
I do not know how I reached this situation - but if I cannot find a solution, it will be the "killer bug" which requires me to replace "Components" with s.th. else...

The environment is as follows:

- I have a "comp start" node with two separate "comp return" nodes (although I do not know if this multiplicity is relevant)
- there are many "comp use" nodes for this "component"

Now, s.th. extremely strange happens:

- when a "msg" enters one "comp use" node, OTHER "comp use" nodes will also emit the result
- for debugging purposes I deleted all incoming wires for those "other" nodes - but they still emit messages

This horribly breaks all my flows which use those "comp use" nodes and even breaks running servers (which are already in use).

As mentioned: I do not know how I reached this situation - the only step taken from the most recently working to the no longer working state was to restart Node-RED

**Comment by ollixx** [comment]
That sounds like an issue.  
Can you send me a flow to reproduce it? I know you can not really track the cause, but maybe you can just send me your complete flow file if it has no secret infos in it. It would of course be very valuable to see, if there is a problem with the events.

**Comment by rozek** [comment]
I'll try to do so - although I already modified the initial flow (for debugging purposes, i.e., to track down the problem). Let me see what I can do for you!

**Comment by ollixx** [comment]
I have a large project and I also see that defect. I will take a look at that soon. It's obviously a problem with the events. It's a. bug.
