### ISSUE TITLE
Return node not working since v0.3.3

### ISSUE THREAD

**Issue by objt-la** [ollixx/node-red-contrib-components#51]
Hi,

I keep getting following error when inserting the 'comp return'. I can't seem to get to work, no matter what I fill in into the name field. Pressing done or deploying first is also not helping.
![image](https://user-images.githubusercontent.com/75269046/146774566-26f3f89e-7814-4719-a7a6-fdf35a1ddc75.png)

**Comment by ollixx** [comment]
I'll take a look at that. Thanks for reporting!

**Comment by ollixx** [comment]
I release 0.3.4 with the bugfix. Check it out, please.

**Comment by objt-la** [comment]
Works like a charm! Thank you.

**Comment by ollixx** [comment]
great!
