### ISSUE TITLE
Using a component node with a jsonata expression is not compatible with Node-RED 3.1

### ISSUE THREAD

**Issue by objt-sb** [ollixx/node-red-contrib-components#60]
When using the "use comp" node with a jsonata expression a warning is triggered in the logs:

![image](https://github.com/ollixx/node-red-contrib-components/assets/62639730/f9a27e19-027a-4f9e-98de-f78cc41899a7)

See: https://nodered.org/blog/2023/09/06/version-3-1-released#deprecating-synchronous-access-to-jsonata

**Comment by ollixx** [comment]
Hi Sander,
thanks for reporting this.

this package was not updated for quite a while. Obviously it's time to do so.

I will try to take a look at that as soon as I have some spare time.

Cheers
:ollix

**Comment by evervondel** [comment]
In node-red 3.1 not using the callback was a warning.
But now in the new 4.1, it is a clear ERROR >> making this usefull node useless.

@ollixx, I can understand you have no spare time to fix this.... is it an option to give me publish rights to be able to update this myself? If not, I will make a fork

**Comment by ollixx** [comment]
Hi evervondel,
I added you here and as a maintainer in npm. 
It's the first time I do this, so let me know, if you need more.
Thanks a lot for taking the initiative, I appreciate it!

**Comment by ollixx** [comment]
yes. I have no scripts for publishing. I did it manually.

**Comment by evervondel** [comment]
I have just published v0.3.6it is now 3.5.1 and 4.x compatible thanks for giving me access!Erwin 
-------- Oorspronkelijk bericht --------Van: ollixx ***@***.***> Datum: 6/07/2024  12:37  (GMT+01:00) Aan: ollixx/node-red-contrib-components ***@***.***> Cc: evervondel ***@***.***>, Comment ***@***.***> Onderwerp: Re: [ollixx/node-red-contrib-components] Using a component node with a jsonata expression is not compatible with Node-RED 3.1 (Issue #60) 
yes. I have no scripts for publishing. I did it manually.
